language: nix
nix: 2.3.5

cache:
  directories:
  - $HOME/nix.store

before_install:
- sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
- nix-channel --add https://nixos.org/channels/nixos-20.03 stable
- nix-channel --add https://nixos.org/channels/nixos-unstable nixos
- nix-channel --update

script: nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=live-usb.nix
